#!/bin/bash
set -e

export SQL_DATABASE=$SQL_DATABASE;
export SQL_HOST=$SQL_HOST;
export SQL_USER=$SQL_USER;
export SQL_PASSWORD=$SQL_PASSWORD;
export SQL_PORT=$SQL_PORT;
export ENV=$ENV;
export SENDGRID_API_KEY=$SENDGRID_API_KEY;